### ISSUE TITLE
沙拉可否检测浏览器进程是否已启用

### ISSUE THREAD

**Issue by qrqhuang** [hqyyqh/Pantherbar-Extensions#1]
神奇的一天， 通过sala发现Pantherbar，然后发现作者大大。

有个问题想咨询下， 假设chrome当前未启动,   可否考虑在ps1中进行检测并自动打开呢，然后才去触发查询热键。

```
while( ! chrome proc exists) {
  start chrome
  sleep 5s
}

send keys.
```

**Comment by hqyyqh** [comment]
> 有个问题想咨询下， 假设 chrome 当前未启动，可否考虑在 ps1 中进行检测并自动打开呢，然后才去触发查询热键。

**不做浏览器启动，主要有以下几个方面的考量：**
1. 除了 chrome ，还有其他基于 Chromium 的浏览器（比如 edge，vivaldi），无法判断需要启动哪个。
2. 给一个选项，用户自己在 `ps1` 中定义浏览器路径。这种修改代码的方式对很多小白用户可能不够友好。
3. 借助[后台运行](https://chrome.google.com/webstore/detail/background-process/alobgnedpnalbocldljnakbbaemakhih?hl=zh-CN)之类的扩展，可以让浏览器开机自启并且后台常驻，就可以完全不需要启动浏览器了。另外，沙拉查词的 [v7.14.0] 版本中[已经加入了后台运行的功能](https://github.com/crimx/ext-saladict/commit/9d41e0980e17dffbcce2804a66b850f9e33c147e)。
![image](https://user-images.githubusercontent.com/38676455/87239298-2d965780-c440-11ea-88f0-ba4d0f13bf1c.png)

----
**题外话：**
[Quicker 动作](https://getquicker.net/sharedaction?code=b0d1a134-8284-4a44-d1be-08d746da5869)比较容易弄一个设置面板，里面是加入了浏览器启动的。而Pantherbar 没有什么可以设计的界面交互🤣🤣。

如果你是想要沙拉查词直接划词翻译的话，上面的 Quicker 动作也是可以的。可以看下[视频演示](https://www.bilibili.com/video/BV1ki4y1x7EN?p=2)，具体实现可以看[文章](https://pencilq.com/65/)。目前还很粗糙，不过用是勉强能用了。

![ ](https://user-images.githubusercontent.com/38676455/87239375-0f7d2700-c441-11ea-862d-7c4a63c2ab99.png)

**Comment by qrqhuang** [comment]
> 借助后台运行之类的扩展，可以让浏览器开机自启并且后台常驻，就可以完全不需要启动浏览器了。另外，沙拉查词的 [v7.14.0] 版本中已经加入了后台运行的功能。

这个可以有，感谢
